name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Release
      uses: qcastel/github-actions-maven-release@v1.12.41
      env:
        JAVA_HOME: $JAVA_HOME_17_x86'.
      with:
        release-branch-name: "main"
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
